version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  topic-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      kafka-topics --create --topic t1_demo_transactions --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 && \
      kafka-topics --create --topic t1_demo_transaction_accept --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 && \
      kafka-topics --create --topic t1_demo_transaction_result --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 && \
      kafka-topics --create --topic t1_demo_metrics --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 && \
      echo 'All topics created.'
      "
