spring.application.name=t1-transaction-listener

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n

server.port=8081

logging.level.root=INFO
logging.level.resenkov.work.task1t1.aop=DEBUG
logging.level.org.springframework.aop=DEBUG
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.data=WARN

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.properties.spring.json.value.default.type=resenkov.work.t1business.entity.Transaction
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.h2.console.enabled=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.url=jdbc:postgresql://localhost:5432/t1_task4
spring.datasource.username=postgres
spring.datasource.password=2611

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.retries=3
spring.kafka.producer.properties.reconnect.backoff.ms=10000
spring.kafka.producer.properties.reconnect.backoff.max.ms=30000
spring.kafka.producer.properties.connections.max.idle.ms=30000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.delivery.timeout.ms=60000
spring.kafka.producer.properties.enable.idempotence=false

spring.kafka.producer.properties.max.block.ms=10000
spring.kafka.admin.fail-fast=true
spring.kafka.admin.properties.retries=1

transaction-check.window-seconds=60
transaction-check.max-tx=15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.fail-on-empty-beans=false

app.metric.timeLimit=10

app.cache.entryTtlMs=60000