spring.application.name=t1-unlock-account


spring.datasource.blacklist.url=jdbc:postgresql://localhost:5432/blacklist
spring.datasource.blacklist.username=postgres
spring.datasource.blacklist.password=2611
spring.datasource.blacklist.driver-class-name=org.postgresql.Driver

spring.datasource.account.url=jdbc:postgresql://localhost:5432/t1_task4
spring.datasource.account.username=postgres
spring.datasource.account.password=2611
spring.datasource.account.driver-class-name=org.postgresql.Driver

unlock.batch-size.clients=3
unlock.batch-size.accounts=5

